### ISSUE TITLE
This example project does not work at all

### ISSUE THREAD

**Issue by rcholic** [hoxton-one/ds-demo-provider#1]
When I start both backend and frontend, I don't see any update or any actions. 

After reading through the code, the data providers are not connected to either the backend of frontend. As a learner still on the learning curve, could you finish this and make it work? thanks

**Comment by yasserf** [comment]
Hey, will take a look at it asap and get back to you.

**Comment by yasserf** [comment]
Hey @rcholic 

I have just run this demo out of the box and it's working minus a bug that is not allowing the stream to unsubscribe.

I just upgraded the dependencies, maybe that would make a difference?

Thanks

**Comment by Lalem001** [comment]
Steps to start, from project root:

Terminal Window/Tab 1:

``` shell
node backend/start-server.js
```

Terminal Window/Tab 2:

``` shell
node backend/fx-data-provider.js
```

Then open `frontend/index.html` in browser.

**Comment by rcholic** [comment]
Thank you very much for the prompt replies. Apparently it was my ignorance that I didn't know I should have run the `fx-data-provider.js` same time. Now everything works! Thanks again!

**Comment by yasserf** [comment]
awesome, thanks @Lalem001, I'll add that to the readme
